import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LenisProvider from "src/components/Animation/LenisProvide";
import { Header } from "src/components/layouts/Header";
import { Footer } from "src/components/layouts/Footer/Footer";
import { GetHomePage } from "src/lib/api/cms";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const api = new GetHomePage();
  const page = await api.fetch();

  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Header data={page.header} global={page.globalSetting} />
        <LenisProvider>{children}</LenisProvider>
        <Footer data={page.footer} global={page.globalSetting} />
      </body>
    </html>
  );
}
